### ISSUE TITLE
Ошибка в скрипте R для карточной сортировки

### ISSUE THREAD

**Issue by menymen7777** [UXRozum/cardsort#1]
Здравствуйте! При выполнении кода из примера появляется ошибка: 
`Error in graph.adjacency.dense(adjmatrix, mode = mode, weighted = weighted, :  At vendor/cigraph/src/constructors/adjacency.c:330 : Edge counts should be non-negative, found -4.85. Invalid value`

Предположительное место возникновения ошибки https://github.com/UXRozum/cardsort/blob/main/CardSort4.R#L122

Я пытался выполнить задание на примере вашего кода, что могло произойти не так?

**Comment by UXRozum** [comment]
Скорее всего у вас очень неравномерно распределены пересечения между карточками, где-то есть большое количество пересечений, где-то их совсем мало, и когда мы отнимаем 1/20 от максимального количества связей, то где-то вылезает негативное количество связей, на что библиотека для создания графов и ругается 

Попробуйте в `max(Adj)*i/20` заменить `20` на `50` или `200` в этой строчке мы считаем, сколько связей отсекать 

Еще можно попробовать построчно выполнить ту часть скрипта, где разделено на шаги, там в шаге 6 можно поиграться с количеством отсекаемых связей

**Comment by menymen7777** [comment]
Спасибо за ответ! Я пробовал повторить быстрый вариант и на вашем примере – ошибка повторялась, поэтому возникло подозрение, что проблема в библиотеке. Также попробовал в функции `max(Adj)*i/20` 20 заменить на 200 и даже на 3000, 50000 – ошибка все равно повторяется

**Comment by UXRozum** [comment]
Надо будет посмотреть, когда будет возможность 
Возможно да, что-то поменялось с момента обновления библиотек, посмотрю

**Comment by menymen7777** [comment]
Спасибо большое!

**Comment by UXRozum** [comment]
Привет! 

Да, судя по всему igraph перестал интерпретировать отрицательные числа в матрице как ноль 
В процессе работы с сетевым графом мы на карточной сортировке получаем много связей всего со всем, и поэтому постепенно отсекаем связи, оставляя только наиболее частые 

Условно, у нас было где-то 5 связей, где-то 25, и убрав 10 мы оставили только более частые 

Я поправил код, в новом релизе нормально работает

**Comment by menymen7777** [comment]
Еще раз спасибо)
